#!/usr/bin/env bash
#
# ./run {day} {part} {data folder} [other arguments]
# eg. ./run day1 one input
#

set -eEuo pipefail

DAY=$1
PART=$2
INPUT=$3

if [ ! -f $INPUT ]; then
    INPUT=$3/$1.txt
fi

cargo run --bin="$DAY" -- $PART $INPUT ${@:4}
